---
# Variables communes Oracle partagées entre tous les rôles
# Ces variables sont automatiquement chargées par Ansible pour tous les hôtes

oracle_version: "19.0.0"
oracle_base: "/u01/app/oracle"
dbhome: "dbhome_1"
oracle_home: "{{ oracle_base }}/product/{{oracle_version}}/{{ dbhome }}"
oracle_inventory: "/u01/app/oraInventory"
oracle_sources: "/u01/sources"
oracle_oradata: "/u02/oradata/"
oracle_fra: "/u03/fast_recovery_area/"

full_configuration: true
secure_configuration: false

scripts_dir: "/home/oracle/scripts"

# Mots de passe utilisateurs système (hashés pour /etc/shadow)
oracle_user_password: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0"
grid_user_password: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0"