---
# Variables par d√©faut surchargeables pour oracle-db-postinstall

scripts_dir: "/home/oracle/scripts"

oracle_version: "19.0.0"
oracle_base: "/u01/app/oracle"
oracle_home: "{{ oracle_base }}/product/{{oracle_version}}/dbhome_1"