---
# roles/oracle-db-install/vars/19c.yml

# Variables pour l'installation d'Oracle 19c
oracle_binary_url: "https://kutt.axiome.io/db19300"
oracle_zip_filename: "LINUX.X64_193000_db_home.zip"

checksum_url: "https://kutt.axiome.io/checksum"

opatch_download_url: "https://kutt.axiome.io/opatch"
opatch_file: "p6880880_190000_Linux-x86-64.zip"

psu_download_url: "https://kutt.axiome.io/db_ru"
psu_file: "p33549642_190000_Linux-x86-64.zip"


# Pour le nom du template de fichier de r√©ponse db_install_19.0.0.j2
db_template_version_string: "19.0.0" 
